### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [Moret84/jte#2]
Dear @Moret84,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by Moret84** [comment]
I saw your issue. I didn't have time. Will do it ASAP.

**Comment by Moret84** [comment]
[Here](https://github.com/Moret84/jte/releases/tag/1.0) we go !

**Comment by sergeevabc** [comment]
Thank you, @Moret84, I see [Taglib][1] supports both *.Opus and *.TTA (True Audio), yet you stripped it?

[1]: http://taglib.org/

**Comment by Moret84** [comment]
Yeah, for now only *.flac and *.mp3 are supported. I didn't know well the formats you mentioned. It seems opus is a Xiph.org format, so it probably uses XiphComment just like Flac. True audio seems to use ID3 tags just like MP3.  All to say it shouldn't be that hard to add support for them.

**Comment by sergeevabc** [comment]
Oh, I thought you attached TagLib with all its features to be available out of the box like [btag][1] does.
Surprised you are not yet familiar with Opus, since it’s even in modern browsers, let alone phones. 
And True Audio (which is indeed rare) uses APEv2, sometimes with ID3 as a backup.
Well, happy tagging MP3 and FLAC then.

[1]: https://github.com/fernandotcl/btag
